### Optimal Fixed/Unfixed Length Plan
![nn](./imgs/Reference%20Graph.png)
- Forward value iteration
- Compute "Cost-to-Come"
- Unfixed-Length

### Import Modules

In [37]:
from math import inf
import numpy as np

### Hyperparameter

In [38]:
start = 1

### Initialization

In [39]:
adj = np.array([[2, 2, inf, inf, inf],
                [inf, inf, 1, 4, inf],
                [1, inf, inf, 1, inf],
                [inf, inf, 1, inf, 1],
                [inf, inf, inf, inf, inf]])

plan = np.full((adj.shape[0]), inf)

plan[start] = 0

### Forward Iteration

In [40]:
prev_plan = np.array([-1, -1, -1, -1, -1])
while not np.array_equal(prev_plan, plan):
    prev_plan = plan
    for src in range(len(plan)):
        if plan[src] < inf:
            local_plan = adj[src, :] + plan[src]
            plan = np.minimum(plan, local_plan)
    print(plan)

[2. 0. 1. 2. 3.]
[2. 0. 1. 2. 3.]


### Result

In [41]:
print(plan)

[2. 0. 1. 2. 3.]
